### ISSUE TITLE
error while

### ISSUE THREAD

**Issue by amiablepk** [ucbvislab/speecheditor#2]
I am getting following error while doing vagrant ssh: Please tell how to solve it.
ERROR: Command errored out with exit status 1: python setup.py egg_info ...
 default: SyntaxError: Unexpected identifier
    default:     at Module._compile (module.js:439:25)
    default:     at Object.Module._extensions..js (module.js:474:10)
    default:     at Module.load (module.js:356:32)
    default:     at Function.Module._load (module.js:312:12)
    default:     at Function.Module.runMain (module.js:497:10)
    default:     at startup (node.js:119:16)
    default:     at node.js:935:3
    default: /usr/lib/node_modules/npm/bin/npm-cli.js:85
    default:       let notifier = require('update-notifier')({pkg})
    default:           ^^^^^^^^
    default: SyntaxError: Unexpected identifier
    default:     at Module._compile (module.js:439:25)
    default:     at Object.Module._extensions..js (module.js:474:10)
    default:     at Module.load (module.js:356:32)
    default:     at Function.Module._load (module.js:312:12)
    default:     at Function.Module.runMain (module.js:497:10)
    default:     at startup (node.js:119:16)
    default:     at node.js:935:3
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by anjandash** [comment]
I have the same error!
In addition, I have Python2.7 related warnings and errors in the log.

**Comment by srubin** [comment]
I updated the installation process - please give it another try (run `vagrant destroy` first to ensure a clean slate).

In general I don't have the time to provide support for this repo, but I'll try to address build issues like this when they arise.

**Comment by amiablepk** [comment]
Thank you very much Sir for taking out time from your busy schedule to
address this. I will check the updated process and try again.
Regards
Praveen

**Comment by thatiraviprasad** [comment]
Hello sir,
Thanks for the update but when i run python app.py 
it is giving error 
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    from mutagen.id3 import ID3
ImportError: No module named mutagen.id3

and when i try to install prerequisities like librosa it gave error 

like 
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

Once again thanks for giving us time and please give us some resolutions to install the specch editor successfully(i am stuck at the last step python app.py).

**Comment by anjandash** [comment]
Well! It works now! Thank you so much @srubin
